spring:
  application:
    name: GREET-API
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
eureka:
    client:
      serviceUrl:
        defaultzone: http://localhost:8761/eureka
        
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
    
server:
  port: 9090
